name = "cf-r2-webdav"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[vars]
USERNAME = "GamerNoTitle"
PASSWORD = "bili33@WPX.Gamer"
BUCKET_NAME = "webdav"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "webdav"